DROP TABLE IF EXISTS urls;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INT AUTO_INCREMENT NOT NULL,
    username VARCHAR(255) UNIQUE NOT NULL,
    userpass VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE urls (
    id INT AUTO_INCREMENT NOT NULL,
    long_url VARCHAR(255) NOT NULL,
    userID INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (userID) REFERENCES users(id)
) AUTO_INCREMENT = 1000000;